# trino-tls-secret.yaml

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trino-tls-secret
  namespace: default
spec:
  secretName: trino-tls-secret
  commonName: trino.k8c.ru
  dnsNames:
    - trino.k8c.ru
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  usages:
    - server auth
    - client auth