# trino-tls-secret.yaml

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trinoid-cert
  namespace: default
spec:
  secretName: trinoid-cert
  commonName: trinoid.k8c.ru
  dnsNames:
    - trinoid.k8c.ru
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  usages:
    - server auth
    - client auth
  
  


# Cert-manager обрабатывает Certificate ресурс:
# Взаимодействует с ClusterIssuer letsencrypt-prod

# Инициирует процесс получения сертификата от Let's Encrypt
# . Процесс выпуска сертификата:
# Проверка домена trino.k8c.ru (обычно через HTTP-01 или DNS-01 challenge)

# Генерация ключевой пары и CSR (Certificate Signing Request)

# Получение подписанного сертификата от Let's Encrypt

# 3. Создание Secret:
# После успешного получения создается Secret trino-tls-secret

# Secret содержит:

# tls.crt - сертификат

# tls.key - приватный ключ

# ca.crt - цепочка доверия (опционально)