# keycloak/keycloak-tls-secret.yaml

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-secret
  namespace: default
spec:
  secretName: keycloak-tls-secret
  commonName: keycloak.k8c.ru
  dnsNames:
    - keycloak.k8c.ru
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  usages:
    - server auth
    - client auth