# # Default values for my-keycloak-chart.
# replicaCount: 1

# image:
#   repository: quay.io/keycloak/keycloak
#   tag: 26.4.2
#   pullPolicy: IfNotPresent

# service:
#   type: ClusterIP
#   port: 8080

# postgres:
#   enabled: true
#   image:
#     repository: postgres
#     tag: 15
#     pullPolicy: IfNotPresent
#   dbUser: keycloak
#   dbPassword: keycloak
#   dbName: keycloak
#   dbHost: postgres
#   dbPort: 5432

# resources:
#   limits:
#     cpu: 2000m
#     memory: 2000Mi
#   requests:
#     cpu: 500m
#     memory: 1700Mi

ingress:
  enabled: 
  name: keycloak-ingress
  host: keycloak.k8c.ru
  secretName: keycloak-tls-secret

