keycloak:
  replicas: 1
  service:
    name: keycloak-service


postgres:
  enabled: true
  serviceName: postgres-service
  image:
    repository: postgres
    tag: 15
    pullPolicy: IfNotPresent
  dbUser: keycloak
  dbPassword: keycloak
  dbName: keycloak
  dbHost: postgres
  dbPort: 5432
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin

ingress:
  enabled: 
  name: keycloak-ingress
  host: keycloak.k8c.ru
  secretName: keycloak-tls-secret

