# Default values for keycloak

replicaCount: 2

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.4.2"
  pullPolicy: IfNotPresent

keycloak:
  adminUser: "admin"
  adminPassword: "admin"
  httpEnabled: true
  proxyHeaders: "xforwarded"
  hostnameStrict: false
  healthEnabled: true
  cache: "ispn"
  
  service:
    type: ClusterIP
    port: 8080
    
  discoveryService:
    type: ClusterIP
    
  resources:
    limits:
      cpu: 2000m
      memory: 2000Mi
    requests:
      cpu: 500m
      memory: 1700Mi
      
  probes:
    startup:
      path: /health/started
      port: 9000
      periodSeconds: 1
      failureThreshold: 600
    readiness:
      path: /health/ready
      port: 9000
      periodSeconds: 10
      failureThreshold: 3
    liveness:
      path: /health/live
      port: 9000
      periodSeconds: 10
      failureThreshold: 3

postgresql:
  enabled: true
  image:
    repository: mirror.gcr.io/postgres
    tag: "17"
    pullPolicy: IfNotPresent
    
  database: "keycloak"
  username: "keycloak"
  password: "keycloak"
  
  service:
    type: ClusterIP
    port: 5432
    
  resources: {}
  
  persistence:
    enabled: false
    # size: 10Gi
    # storageClass: ""
    