{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-postgres
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
  type: {{ .Values.postgresql.service.type }}
{{- end }}
