apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.keycloak.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  type: {{ .Values.keycloak.service.type }}
  