# go-server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment  # Different from Docker container_name
  labels:
    app: backend
    component: server
    tier: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      component: server
  template:
    metadata:
      labels:
        app: backend
        component: server
        tier: application
    spec:
      containers:
      - name: server-container  # Different from Docker container_name
        image: naeel/iman:latest
        env:
        - name: DATABASE_DSN
          value: "host=postgres-service user=uname password=parole dbname=dbase sslmode=disable"
        - name: ADDRESS
          value: ":8080"
        ports:
        - containerPort: 8080
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
      restartPolicy: Always