# postgres-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "metadb"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 256MB
    effective_cache_size = 1GB

    # psql -U user -d metadb
