apiVersion: v2
appVersion: 12.0.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/cloudpirates
  version: 2.x.x
description: MariaDB is a high-performance, open-source relational database server
  that is a drop-in replacement for MySQL
home: https://www.cloudpirates.io
icon: https://a.storyblok.com/f/143071/512x512/6512dd22ee/mariadb-logo.svg
keywords:
- mariadb
- mysql
- database
- sql
- relational
maintainers:
- name: CloudPirates GmbH & Co. KG
  url: https://www.cloudpirates.io
name: mariadb
sources:
- https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mariadb
type: application
version: 0.4.0
