{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-keycloak-chart.fullname" . }}-ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ index (.Values.ingress.tls | first).secretName }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .paths.path }}
            pathType: {{ .paths.pathType }}
            backend:
              service:
                name: {{ include "my-keycloak-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
{{- end }}
