{{- if .Values.keycloak.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  annotations:
    {{- range $key, $value := .Values.keycloak.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.keycloak.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.keycloak.host }}
      secretName: {{ .Values.keycloak.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.keycloak.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-keycloak
                port:
                  number: 8080
{{- end }}
