# trino/templates/configmap-etc.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-config
data:
      # конфигурация соответствует установке одиночного узла (single-node setup) для Trino
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    discovery.uri=http://localhost:8080
    # server.port=8080

  jvm.config: |
    -server
    -Xmx1G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+UseGCOverheadLimit
    -XX:+ExitOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=256M
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000

  node.properties: |
    node.environment=docker
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin
