apiVersion: v2
appVersion: "18.0"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/cloudpirates
  version: 2.x.x
description: The World's Most Advanced Open Source Relational Database
home: https://www.cloudpirates.io
icon: https://a.storyblok.com/f/143071/512x512/95e7f13e62/postgres-logo.svg
keywords:
- postgres
- postgresql
- database
- sql
- relational
maintainers:
- name: CloudPirates GmbH & Co. KG
  url: https://www.cloudpirates.io
name: postgres
sources:
- https://github.com/CloudPirates-io/helm-charts/tree/main/charts/postgres
type: application
version: 0.9.0
