# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-service  # Service name referenced in StatefulSet
  labels:
    app: backend
    component: database-service
spec:
  selector:
    app: backend
    component: database
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None  # Important for StatefulSet DNS resolution


