{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "postgres.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "postgres.fullname" .)) }}
  {{- $existingPostgresPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingPostgresPassword = index $existingSecret.data "postgres-password" }}
  {{- end }}
  {{- $postgresPassword := $existingPostgresPassword | default (.Values.auth.password | default (randAlphaNum 32) | b64enc) }}
  {{- $host := printf "%s.%s.svc" (include "postgres.fullname" .) .Release.Namespace }}
  {{- $port := .Values.service.port | toString }}
  {{- $username := include "postgres.username" . }}
  {{- $database := include "postgres.database" . }}
  postgres-password: {{ $postgresPassword | quote }}
  host: {{ $host | b64enc | quote }}
  port: {{ $port | b64enc | quote }}
  username: {{ $username | b64enc | quote }}
  database: {{ $database | b64enc | quote }}
  uri: {{ printf "postgresql://%s:%s@%s:%s/%s" $username ($postgresPassword | b64dec) $host $port $database | b64enc | quote }}
{{- end }}
