# pgadmin-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: admin
    component: pgadmin-service
spec:
  type: NodePort
  selector:
    app: admin
    component: pgadmin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081  # Accessible on Minikube at this port
    